export const SWITCH_PLAYBACK_STATE = "SWITCH_PLAYBACK_STATE";
export const CHANGE_VOLUME = "CHANGE_VOLUME";
export const CHANGE_SONG = "CHANGE_SONG";
export const UPDATE_SEARCH_TERM = "UPDATE_SEARCH_TERM";
export const UPDATE_PLAYBACK_POSITION = "UPDATE_PLAYBACK_POSITION";
export const FETCH_PLAYLIST_REQUESTED = "FETCH_PLAYLIST_REQUESTED";
export const FETCH_PLAYLIST_SUCCEEDED = "FETCH_PAYLIST_SUCCEEDED";
export const FETCH_PLAYLIST_FAILED = "FETCH_PLAYLIST_FAILED";
